application: YOUR_APPLICATION_NAME_HERE
version: 1
runtime: python
api_version: 1


handlers:

- url: /_ah/login_required
  script: do_openid_login.py

- url: /css
  static_dir: css

- url: .*
  script: main.py

- url: /(.*)
  script: main.py


